import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
dotenv.config({ path: '.env.local' });

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const products = [
  // ── MEDICINES ──────────────────────────────────────────────────────────────
  {
    name: 'Paracetamol 500mg',
    category: 'medicine',
    manufacturer: 'Emzor Pharmaceuticals',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'EM-2024-001',
    expiry_date: '2026-06-30',
    barcode: '6934567890123',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 90,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Amoxicillin 250mg Capsules',
    category: 'medicine',
    manufacturer: 'May & Baker Nigeria',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'MB-2024-055',
    expiry_date: '2025-12-31',
    barcode: '6934567890124',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 85,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Metronidazole 400mg',
    category: 'medicine',
    manufacturer: 'Fidson Healthcare',
    manufacturer_verified: false,
    country_of_origin: 'Nigeria',
    batch_number: 'FH-2024-022',
    expiry_date: '2026-03-31',
    barcode: '6934567890125',
    status: 'under_review',
    verified_by_authority: false,
    trust_score: 55,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Vitamin C 1000mg (Unbranded)',
    category: 'medicine',
    manufacturer: 'Unknown Importer',
    manufacturer_verified: false,
    country_of_origin: null,
    batch_number: null,
    expiry_date: '2025-08-31',
    barcode: '6934567890126',
    status: 'suspected_counterfeit',
    verified_by_authority: false,
    trust_score: 20,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Artemether-Lumefantrine 20/120mg (Coartem)',
    category: 'medicine',
    manufacturer: 'Novartis',
    manufacturer_verified: true,
    country_of_origin: 'Switzerland',
    batch_number: 'NV-2024-AL88',
    expiry_date: '2026-09-30',
    barcode: '6934567890127',
    status: 'recalled',
    verified_by_authority: true,
    trust_score: 10,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Chloroquine Phosphate 250mg',
    category: 'medicine',
    manufacturer: 'Swipha',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'SW-2024-CQ10',
    expiry_date: '2025-09-30',
    barcode: '6934567890128',
    status: 'recalled',
    verified_by_authority: true,
    trust_score: 8,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Ciprofloxacin 500mg Tablets',
    category: 'medicine',
    manufacturer: 'Pfizer',
    manufacturer_verified: true,
    country_of_origin: 'USA',
    batch_number: 'PF-2024-CP31',
    expiry_date: '2027-01-31',
    barcode: '6934567890129',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 93,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Oral Rehydration Salt (ORS)',
    category: 'medicine',
    manufacturer: 'UNICEF Supply Division',
    manufacturer_verified: true,
    country_of_origin: 'Denmark',
    batch_number: 'UN-2024-ORS5',
    expiry_date: '2027-06-30',
    barcode: '6934567890130',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 95,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Fake Anti-Malaria Tablets (Counterfeit)',
    category: 'medicine',
    manufacturer: 'Unknown',
    manufacturer_verified: false,
    country_of_origin: null,
    batch_number: 'XX-0000',
    expiry_date: null,
    barcode: '0000000000001',
    status: 'suspected_counterfeit',
    verified_by_authority: false,
    trust_score: 5,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Ibuprofen 400mg Tablets',
    category: 'medicine',
    manufacturer: 'GlaxoSmithKline',
    manufacturer_verified: true,
    country_of_origin: 'UK',
    batch_number: 'GSK-2024-IB77',
    expiry_date: '2026-11-30',
    barcode: '6934567890131',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 89,
    source: 'marksure',
    image_url: null,
  },

  // ── COSMETICS ──────────────────────────────────────────────────────────────
  {
    name: 'Fair & White Cream',
    category: 'cosmetic',
    manufacturer: 'Fair & White',
    manufacturer_verified: false,
    country_of_origin: 'France',
    batch_number: 'FW-2024-B12',
    expiry_date: '2026-01-31',
    barcode: '3760033630215',
    status: 'under_review',
    verified_by_authority: false,
    trust_score: 45,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Nivea Body Lotion (200ml)',
    category: 'cosmetic',
    manufacturer: 'Beiersdorf AG',
    manufacturer_verified: true,
    country_of_origin: 'Germany',
    batch_number: 'BF-2024-NV99',
    expiry_date: '2027-01-31',
    barcode: '4005900444554',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 92,
    source: 'marksure',
    image_url: 'https://images.openbeautyfacts.org/images/products/400/590/044/4554/front_fr.12.400.jpg',
  },
  {
    name: 'Shea Butter Pure Organic',
    category: 'cosmetic',
    manufacturer: 'AfriNatural Ltd',
    manufacturer_verified: false,
    country_of_origin: 'Ghana',
    batch_number: null,
    expiry_date: null,
    barcode: null,
    status: 'unknown',
    verified_by_authority: false,
    trust_score: 30,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Fake Bleaching Cream (Unbranded)',
    category: 'cosmetic',
    manufacturer: 'Unknown',
    manufacturer_verified: false,
    country_of_origin: null,
    batch_number: 'X-9999',
    expiry_date: null,
    barcode: '9999999999999',
    status: 'suspected_counterfeit',
    verified_by_authority: false,
    trust_score: 5,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Dettol Antiseptic Liquid (250ml)',
    category: 'cosmetic',
    manufacturer: 'Reckitt Benckiser',
    manufacturer_verified: true,
    country_of_origin: 'UK',
    batch_number: 'RB-2024-DT66',
    expiry_date: '2027-06-30',
    barcode: '6001087340255',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 94,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Vaseline Petroleum Jelly (250ml)',
    category: 'cosmetic',
    manufacturer: 'Unilever',
    manufacturer_verified: true,
    country_of_origin: 'USA',
    batch_number: 'UL-2024-VJ55',
    expiry_date: '2028-03-31',
    barcode: '3017620422003',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 91,
    source: 'marksure',
    image_url: null,
  },

  // ── FOOD ───────────────────────────────────────────────────────────────────
  {
    name: 'Indomie Noodles Chicken Flavour',
    category: 'food',
    manufacturer: 'Dufil Prima Foods',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'DP-2024-CF77',
    expiry_date: '2025-11-30',
    barcode: '0089686170115',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 88,
    source: 'marksure',
    image_url: 'https://images.openfoodfacts.org/images/products/008/968/617/0115/front_en.39.400.jpg',
  },
  {
    name: 'Peak Full Cream Milk Powder (400g)',
    category: 'food',
    manufacturer: 'FrieslandCampina WAMCO',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'FC-2024-PK44',
    expiry_date: '2026-04-30',
    barcode: '8716200449274',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 91,
    source: 'marksure',
    image_url: 'https://images.openfoodfacts.org/images/products/871/620/044/9274/front_en.7.400.jpg',
  },
  {
    name: 'Milo Energy Drink (400g)',
    category: 'food',
    manufacturer: 'Nestlé Nigeria',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'NN-2024-ML33',
    expiry_date: '2026-02-28',
    barcode: '0055000917421',
    status: 'under_review',
    verified_by_authority: false,
    trust_score: 60,
    source: 'marksure',
    image_url: 'https://images.openfoodfacts.org/images/products/005/500/091/7421/front_en.16.400.jpg',
  },
  {
    name: 'Fake Honey (Adulterated)',
    category: 'food',
    manufacturer: 'Unknown',
    manufacturer_verified: false,
    country_of_origin: null,
    batch_number: null,
    expiry_date: null,
    barcode: '1234567891234',
    status: 'suspected_counterfeit',
    verified_by_authority: false,
    trust_score: 15,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Golden Morn Maize Oats (500g)',
    category: 'food',
    manufacturer: 'Nestlé Nigeria',
    manufacturer_verified: true,
    country_of_origin: 'Nigeria',
    batch_number: 'NN-2024-GM19',
    expiry_date: '2025-10-31',
    barcode: '6033000680389',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 87,
    source: 'marksure',
    image_url: 'https://images.openfoodfacts.org/images/products/603/300/068/0389/front_en.1.400.jpg',
  },
  {
    name: 'Counterfeit Digestive Biscuit',
    category: 'food',
    manufacturer: 'Unknown Factory',
    manufacturer_verified: false,
    country_of_origin: null,
    batch_number: null,
    expiry_date: '2024-01-01',
    barcode: '0000000000002',
    status: 'suspected_counterfeit',
    verified_by_authority: false,
    trust_score: 12,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Lipton Yellow Label Tea (100 bags)',
    category: 'food',
    manufacturer: 'Unilever',
    manufacturer_verified: true,
    country_of_origin: 'Kenya',
    batch_number: 'UL-2024-LT88',
    expiry_date: '2026-12-31',
    barcode: '8720608011599',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 90,
    source: 'marksure',
    image_url: 'https://images.openfoodfacts.org/images/products/872/060/801/1599/front_fr.20.400.jpg',
  },
  {
    name: 'Tomato Paste (Recalled Batch)',
    category: 'food',
    manufacturer: 'Unknown',
    manufacturer_verified: false,
    country_of_origin: null,
    batch_number: null,
    expiry_date: '2023-06-01',
    barcode: '0000000000003',
    status: 'recalled',
    verified_by_authority: false,
    trust_score: 5,
    source: 'marksure',
    image_url: null,
  },
  {
    name: 'Quaker Oats (1kg)',
    category: 'food',
    manufacturer: 'PepsiCo / Quaker',
    manufacturer_verified: true,
    country_of_origin: 'USA',
    batch_number: 'QK-2024-OT55',
    expiry_date: '2026-08-31',
    barcode: '5000108022152',
    status: 'verified_safe',
    verified_by_authority: true,
    trust_score: 93,
    source: 'marksure',
    image_url: 'https://images.openfoodfacts.org/images/products/500/010/802/2152/front_en.61.400.jpg',
  },
];

async function seed() {
  console.log('🌱 Seeding products...');

  // Clear existing seed data
  const { error: deleteError } = await supabase
    .from('products')
    .delete()
    .eq('source', 'marksure');

  if (deleteError) {
    console.error('Error clearing existing data:', deleteError.message);
    process.exit(1);
  }

  const { data, error } = await supabase
    .from('products')
    .insert(products)
    .select('id, name');

  if (error) {
    console.error('Seed error:', error.message);
    process.exit(1);
  }

  console.log(`✅ Seeded ${data?.length} products:`);
  data?.forEach((p) => console.log(`   - ${p.name}`));

  // Add 3 pending reports for demo products
  const reported = data?.filter((_, i) => i === 2 || i === 7 || i === 12); // Metronidazole, Fake Anti-Malaria, Shea Butter
  if (reported && reported.length > 0) {
    const reports = reported.map((p) => ({
      product_id: p.id,
      description: 'Suspected packaging irregularity — label fonts do not match official product.',
      anonymous: true,
      status: 'pending',
    }));
    const { error: reportError } = await supabase.from('reports').insert(reports);
    if (reportError) {
      console.error('Report seed error:', reportError.message);
    } else {
      console.log(`✅ Added ${reports.length} demo reports`);
    }
  }

  console.log('\n🎉 Seed complete!');
  process.exit(0);
}

seed();